=== Activiti/activiti-cloud/activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/resources/schema/connector-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Connector editor schema",
  "description": "Connector editor schema",
  "type": "object",

  "definitions": {
    "connector-parameters": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties" : false,
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "description": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [ "string", "integer", "boolean", "date", "json", "file" ]
          },
          "required": {
            "type": "boolean"
          }
        },
        "required": [ "id", "name", "type" ]
      }
    },
    "connector-action": {
      "type": "object",
      "additionalProperties" : false,
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string"
        },
        "inputs": { "$ref": "#/definitions/connector-parameters" },
        "outputs": { "$ref": "#/definitions/connector-parameters" }
      },
      "required": [ "id", "name" ]
    }
  },

  "additionalProperties" : false,
  "properties": {
    "id": {
      "description": "The connector id",
      "type": "string"
    },
    "name": {
      "description": "The connector's name",
      "type": "string",
      "minLength": 1,
      "maxLength": 26,
      "pattern": "^[a-z]([-a-z0-9]{0,24}[a-z0-9])?$"
    },
    "description": {
      "description": "The connector's description",
      "type": "string"
    },
    "template": {
      "description": "The connector's template",
      "type": "string"
    },
    "actions" : {
      "type": "object",
      "additionalProperties": { "$ref": "#/definitions/connector-action" },
      "default": {}
    }
  },
  "required": [ "name" ]
}

=== Activiti/activiti-cloud/activiti-cloud-starter-runtime-bundle/src/test/resources/connectors/rest.json
{
  "id": "connector-53f47c39-111d-49cc-88f5-7bd960b387e3",
  "name": "rest",
  "description": "APS Connector that provides an HTTP client for consuming any REST service",
  "actions": {
    "0d06f1c3-ede6-498a-9ca6-e0ac0f1c9213": {
      "id": "0d06f1c3-ede6-498a-9ca6-e0ac0f1c9213",
      "name": "GET",
      "description": "Invokes the HTTP GET method to get data from a specific resource.",
      "inputs": [
        {
          "id": "96f9f56e-01d3-4c89-a50e-6821b2e92b55",
          "name": "restUrl",
          "description": "URL of the REST endpoint including protocol, host and path.",
          "type": "string",
          "required": true
        },
        {
          "id": "22b519bc-3bc0-4bf9-918c-307fd5c043b1",
          "name": "restUrlParams",
          "description": "URL params to append to the url.",
          "type": "string",
          "required": false
        },
        {
          "id": "fc544981-0638-474b-a085-d07c87dc7221",
          "name": "requestHeaders",
          "description": "Map of request header names and values. Values can be fixed values, variables or form fields.",
          "type": "string",
          "required": false
        },
        {
          "id": "de9961d8-6567-4543-baf3-93c90fce603f",
          "name": "circuitBreaker",
          "description": "If this variable is present and true with any value, the circuit breaker is enabled.",
          "type": "boolean",
          "required": false
        },
        {
          "id": "a5ec3067-38c1-4351-be77-5e60423371a6",
          "name": "timeout",
          "description": "Integer with the timeout call in milliseconds.",
          "type": "boolean"
        },
        {
          "id": "210a96d7-b9ad-41c8-bce5-fcc00b626af8",
          "name": "restUrlEncoded",
          "description": "Indicates whether the final URL should be encoded or not",
          "type": "boolean"
        }
      ],
      "outputs": [
        {
          "id": "7a6fd408-3912-4253-98ea-e19be43a8447",
          "name": "restResult",
          "description": "The response from the REST service call",
          "type": "string"
        },
        {
          "id": "f4d19b9c-876f-4c59-bfa6-3e3067901881",
          "name": "restError",
          "description": "Error description when an error occurs calling the REST service",
          "type": "string"
        },
        {
          "id": "d2b5bec0-2c73-46ce-83f5-3d39a23e3b75",
          "name": "restStatus",
          "description": "HTTP response status code",
          "type": "integer"
        }
      ]
    },
    "9718c25a-0f3c-4ad2-85d4-148111ca4d4a": {
      "id": "9718c25a-0f3c-4ad2-85d4-148111ca4d4a",
      "name": "POST",
      "description": "Invokes the HTTP POST method to send data to a server to create/update a resource.",
      "inputs": [
        {
          "id": "6e79e5e5-71ef-4915-b918-5c34f6e87d52",
          "name": "restUrl",
          "description": "URL of the REST endpoint including protocol, host and path.",
          "type": "string",
          "required": false
        },
        {
          "id": "c048e6f7-1dad-4ef1-9bae-39c8282a85a7",
          "name": "restUrlParams",
          "description": "URL params to append to the url.",
          "type": "string",
          "required": false
        },
        {
          "id": "98e3fa15-bf7b-4402-8a93-79be619de64f",
          "name": "requestPayload",
          "description": "Map of JSON properties and values to compose the request payload. Values can be fixed values, variables or form fields.",
          "type": "string",
          "required": false
        },
        {
          "id": "7b48ca8b-8b07-4a67-ade9-2abf7a8b448a",
          "name": "requestHeaders",
          "description": "Map of request header names and values. Values can be fixed values, variables or form fields.",
          "type": "string",
          "required": false
        },
        {
          "id": "d6e72d4a-8d59-41cc-9655-e22ff3f5dd81",
          "name": "circuitBreaker",
          "description": "If this variable is present with any value, the circuit breaker is enabled.",
          "type": "boolean",
          "required": false
        },
        {
          "id": "28deba6c-3104-4310-9c4b-f747c370aca2",
          "name": "timeout",
          "description": "Integer with the timeout call in milliseconds.",
          "type": "integer",
          "required": false
        },
        {
          "id": "9f6f0688-16ee-472a-abdf-baef6caaea02",
          "name": "restUrlEncoded",
          "description": "Indicates whether the final URL should be encoded or not",
          "type": "boolean"
        }
      ],
      "outputs": [
        {
          "id": "5cebbf70-2408-4dd6-86e7-7c1eb77658d9",
          "name": "restResult",
          "description": "The response from the REST service call",
          "type": "string"
        },
        {
          "id": "15bca89a-3527-46c2-8433-524a6d0a7702",
          "name": "restError",
          "description": "Error description when an error occurs calling the REST service",
          "type": "string"
        },
        {
          "id": "c0f62a79-e1df-4d7c-9a4d-4ef0d211a8d2",
          "name": "restStatus",
          "description": "HTTP response status code",
          "type": "integer"
        }
      ]
    },
    "48a9c52c-faf8-4ebd-bfcc-884002e1a0df": {
      "id": "48a9c52c-faf8-4ebd-bfcc-884002e1a0df",
      "name": "PUT",
      "description": "Invokes the PUT HTTP method to send data to a server to create/update a resource.",
      "inputs": [
        {
          "id": "e341d517-c842-4d53-b678-abe6794424b1",
          "name": "restUrl",
          "description": "URL of the REST endpoint including protocol, host and path.",
          "type": "string",
          "required": true
        },
        {
          "id": "7a2aba34-103a-40e8-bb40-616e1535e789",
          "name": "restUrlParams",
          "description": "URL params to append to the url.",
          "type": "string",
          "required": false
        },
        {
          "id": "8c55682d-5aba-4d6c-bcd9-20545286b2fd",
          "name": "requestPayload",
          "description": "Map of JSON properties and values to compose the request payload. Values can be fixed values, variables or form fields.",
          "type": "string",
          "required": false
        },
        {
          "id": "9bffbc7a-2c42-4746-a802-e367ba2e683b",
          "name": "requestHeaders",
          "description": "Map of request header names and values. Values can be fixed values, variables or form fields.",
          "type": "string",
          "required": false
        },
        {
          "id": "b5e43c1d-06c3-472a-b4ff-72adaf689095",
          "name": "circuitBreaker",
          "description": "If this variable is present with any value, the circuit breaker is enabled.",
          "type": "boolean",
          "required": false
        },
        {
          "id": "efeadbe9-3526-42bb-b129-78f6ff9376e6",
          "name": "timeout",
          "description": "Integer with the timeout call in milliseconds.",
          "type": "integer",
          "required": false
        },
        {
          "id": "2afa3b18-5cb9-408d-b0cf-ea7d4bfae7a9",
          "name": "restUrlEncoded",
          "description": "Indicates whether the final URL should be encoded or not",
          "type": "boolean"
        }
      ],
      "outputs": [
        {
          "id": "a5587a45-675e-4197-a949-4f9c2153cfdf",
          "name": "restResult",
          "description": "The response from the REST service call",
          "type": "string"
        },
        {
          "id": "a872a945-d836-4066-98f2-d6211c14e104",
          "name": "restError",
          "description": "Error description when an error occurs calling the REST service",
          "type": "string"
        },
        {
          "id": "d0456ee8-bfa7-4987-9c8f-b87f9a00685c",
          "name": "restStatus",
          "description": "HTTP response status code",
          "type": "integer"
        }
      ]
    },
    "ec357914-11f2-448c-bf82-f02b93e816c2": {
      "id": "ec357914-11f2-448c-bf82-f02b93e816c2",
      "name": "PATCH",
      "description": "Invokes the PATCH HTTP method to apply partial modifications to a resource",
      "inputs": [
        {
          "id": "7b7d3626-1127-4b77-8c2a-0aa79fb62387",
          "name": "restUrl",
          "description": "URL of the REST endpoint including protocol, host and path.",
          "type": "string"
        },
        {
          "id": "1c47e15d-5d16-41d4-9c33-219b8b4c7117",
          "name": "restUrlParams",
          "description": "URL params to append to the url.",
          "type": "string",
          "required": false
        },
        {
          "id": "61c918d7-6171-4fc4-b7ff-42ce04f95bfe",
          "name": "requestPayload",
          "description": "Map of JSON properties and values to compose the request payload. Values can be fixed values, variables or form fields.",
          "type": "string",
          "required": false
        },
        {
          "id": "9b4a704f-fa7a-4f13-bc85-b263211e7b42",
          "name": "requestHeaders",
          "description": "Map of request header names and values. Values can be fixed values, variables or form fields.",
          "type": "string",
          "required": false
        },
        {
          "id": "861576b1-9d5e-4058-91e2-f2a641918c1d",
          "name": "circuitBreaker",
          "description": "If this variable is present with any value, the circuit breaker is enabled.",
          "type": "boolean",
          "required": false
        },
        {
          "id": "9c7786ee-f763-4a3f-8241-630428ddaa89",
          "name": "timeout",
          "description": "HTTP request timeout in milliseconds",
          "type": "integer",
          "required": false
        },
        {
          "id": "2a85c388-4ca8-4d63-802f-f4c1f945bb84",
          "name": "restUrlEncoded",
