=== Activiti/activiti-cloud/activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/resources/schema/process-extensions-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Process extensions schema",
  "description": "Process extensions schema",
  "type": "object",
  "definitions": {
    "extensions": {
      "type": "object",
      "properties": {
        "properties": {
          "description": "The extensions properties",
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/properties"
          }
        },
        "mappings": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "propertyNames": {
              "type": "string",
              "enum": [
                "inputs",
                "outputs"
              ]
            },
            "additionalProperties": {
              "type": "object",
              "additionalProperties": {
                "type": "object",
                "$ref": "#/definitions/mappings"
              }
            }
          }
        },
        "constants": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "$ref": "#/definitions/constants"
            }
          }
        }
      }
    },
    "properties": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "date",
            "string",
            "integer",
            "boolean",
            "json"
          ]
        },
        "required": {
          "type": "boolean"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "date"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "string",
                "pattern": "^[0-9]{4}-(((0[13578]|(10|12))-(0[1-9]|[1-2][0-9]|3[0-1]))|(02-(0[1-9]|[1-2][0-9]))|((0[469]|11)-(0[1-9]|[1-2][0-9]|30)))$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "string"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "string"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "integer"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "integer"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "boolean"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "boolean"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "json"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "object"
              }
            }
          }
        }
      ],
      "required": [
        "id",
        "name",
        "type",
        "required"
      ]
    },
    "mappings": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "variable",
            "value"
          ]
        },
        "value": {
          "type": "string"
        }
      },
      "dependencies": {
        "type": [
          "value"
        ],
        "value": [
          "type"
        ]
      }
    },
    "constants": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      }
    }
  },
  "properties": {
    "id": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "extensions": {
      "$ref": "#/definitions/extensions"
    }
  },
  "required": [
    "id"
  ]
}

=== Activiti/activiti-cloud/activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/resources/processes/variable-mapping-with-loop-extensions.json
{
  "id": "process-fdee92a0-5a2b-48be-8696-245eff49aa07",
  "type": "PROCESS",
  "name": "variable-mapping-with-loop",
  "extensions": {
    "Process_N4qkN051N": {
      "constants": {},
      "mappings": {
        "Task_0od1320": {
          "outputs": {
            "processedValue": {
              "type": "variable",
              "value": "output"
            }
          },
          "inputs": {
            "input": {
              "type": "variable",
              "value": "input"
            }
          }
        },
        "Task_125yjke": {
          "outputs": {
            "input": {
              "type": "variable",
              "value": "formInput"
            }
          }
        }
      },
      "properties": {
        "d9ab5d53-3dba-4422-9ba7-b74dc216d1ba": {
          "id": "d9ab5d53-3dba-4422-9ba7-b74dc216d1ba",
          "name": "input",
          "type": "string",
          "value": "",
          "required": false
        },
        "e974d84d-aa76-4acb-903d-97582fe89861": {
          "id": "e974d84d-aa76-4acb-903d-97582fe89861",
          "name": "processedValue",
          "type": "string",
          "value": "",
          "required": false
        }
      },
      "assignments": {
        "Task_125yjke": {
          "type": "identity",
          "assignment": "assignee",
          "id": "Task_125yjke"
        }
      }
    }
  }
}

=== Activiti/activiti-cloud/activiti-cloud-starter-runtime-bundle/src/test/resources/processes/throwmessagemapping-extensions.json
{
  "id": "process-be954b8b-b412-4fcb-9fc5-bf1d096d249f",
  "type": "PROCESS",
  "name": "throwmessagemapping",
  "extensions": {
    "process-be954b8b-b412-4fcb-9fc5-bf1d096d249f": {
      "constants": {},
      "mappings": {
        "IntermediateThrowEvent_0d3t2mv": {
          "inputs": {
            "stringvar": {
              "type": "value",
              "value": "string"
            },
            "variablevar": {
              "type": "variable",
              "value": "variable"
            }
          }
        }
      },
      "properties": {
        "a1279632-75cd-42c7-81d1-648f9e0483d6": {
          "id": "a1279632-75cd-42c7-81d1-648f9e0483d6",
          "name": "corr",
          "type": "string",
          "value": "corr",
          "required": false
        },
        "20681f63-0b1a-4e2c-92fc-442536f3168c": {
          "id": "20681f63-0b1a-4e2c-92fc-442536f3168c",
          "name": "variable",
          "type": "string",
          "value": "default",
          "required": false
        }
      }
    }
  }
}

=== Activiti/activiti-cloud/activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/resources/process-extensions/message-payload-extension.json
{
  "id": "process-db995012-b417-4cea-a981",
  "type": "PROCESS",
  "name": "Message Payload Process",
  "extensions": {
    "Process_hg2itgWRj": {
      "constants": {},
      "mappings": {
        "IntermediateThrowEvent_1kozj3g": {
          "inputs": {
            "my-message-payload": {
              "type": "variable",
              "value": "var1"
            },
            "goodPayload": {
              "type": "variable",
              "value": "var1"
            },
            "wrong-payload": {
              "type": "variable",
              "value": "var1"
            },
            "123abc": {
              "type": "variable",
              "value": "var1"
            }
          }
        }
      },
      "properties": {
        "ca9de08b-2ac7-4e1c-86bb-86e01c71b536": {
          "id": "ca9de08b-2ac7-4e1c-86bb-86e01c71b536",
          "name": "correlationkey",
          "type": "string",
          "value": "test",
          "required": false
        },
        "f829e900-e5f3-4ccb-bcd5-5c29097d7743": {
          "id": "f829e900-e5f3-4ccb-bcd5-5c29097d7743",
          "name": "var1",
          "type": "string",
          "value": "",
          "required": false
        }
      },
      "assignments": {}
    },
    "Process_1mzy483": {
      "constants": {},
      "mappings": {
        "IntermediateThrowEvent_07o1f9u": {
          "outputs": {
            "var1": {
              "type": "variable",
              "value": "my-message-payload"
            }
          }
        }
      },
      "properties": {
        "d649ed6b-d40c-44f3-a9bd-907f01c759c4": {
          "id": "d649ed6b-d40c-44f3-a9bd-907f01c759c4",
          "name": "correlationkey",
          "type": "string",
          "value": "test",
          "required": false
        },
        "44cb1052-72fc-4cf0-aa48-8dd589567e60": {
          "id": "44cb1052-72fc-4cf0-aa48-8dd589567e60",
          "name": "var1",
          "type": "string",
          "value": "",
          "required": false
        }
      },
      "assignments": {}
    }
  }
}

=== Activiti/activiti-cloud/activiti-cloud-starter-runtime-bundle/src/test/resources/processes/catchmessagemapping-extensions.json
{
  "id": "process-bf064b4f-5cf7-440c-b6b1-e55ac532e56c",
  "type": "PROCESS",
  "name": "catchmessagemapping",
  "extensions": {
    "constants": {
    },
    "mappings": {
      "IntermediateCatchEvent_1yibl67": {
        "outputs": {
          "string": {
            "type": "variable",
            "value": "stringvar"
          },
          "variable": {
            "type": "variable",
            "value": "variablevar"
          }
        }
      },
      "UserTask_0ghvi9h": {
        "inputs": {
          "Text07gqlq": {
            "type": "variable",
            "value": "string"
          },
          "Text0hs9l0": {
            "type": "variable",
            "value": "variable"
          }
        }
      }
    },
    "properties": {
      "a1279632-75cd-42c7-81d1-648f9e0483d6": {
        "id": "a1279632-75cd-42c7-81d1-648f9e0483d6",
        "name": "corr",
        "type": "string",
        "value": "corr",
        "required": false
      },
      "20681f63-0b1a-4e2c-92fc-442536f3168c": {
        "id": "20681f63-0b1a-4e2c-92fc-442536f3168c",
        "name": "variable",
        "type": "string",
        "value": "",
        "required": false
      },
      "b42b86b9-f9b0-466a-988c-167fd3aeb794": {
        "id": "b42b86b9-f9b0-466a-988c-167fd3aeb794",
        "name": "string",
        "type": "string",
        "value": "",
        "required": false
      }
    }
  }
}

=== Activiti/activiti-cloud/activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/resources/process-extensions/valid-extensions-with-variable-bigdecimal-as-expression.json
{
  "id": "process-id",
  "type": "PROCESS",
  "name": "process-test",
  "extensions": {
    "Process_test": {
      "properties": {
        "8b9ac008-8a76-4ebd-8221-04452add5f22": {
          "id": "8b9ac008-8a76-4ebd-8221-04452add5f22",
          "name": "var1",
          "type": "bigdecimal",
          "value": "${expression.test}",
          "required": false
        }
      }
    }
  }
}

=== Activiti/activiti-cloud/example-runtime-bundle/starter/src/main/resources/processes/multiinstance-servicetask-extensions.json
{
  "id": "process-3de93c0a-abd3-413b-98d2-bfb830bec152",
  "type": "PROCESS",
  "name": "multiinstance-servicetask",
  "extensions": {
    "Process_B-f96qb1": {
      "constants": {},
      "mappings": {
        "ServiceTask_0qp1237": {
          "inputs": {
            "restUrl": {
              "type": "value",
              "value": "https://jsonplaceholder.typicode.com/posts"
            },
            "requestPayload": {
              "type": "value",
              "value": "{     \"userId\": 1,     \"id\": 1,     \"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",     \"body\": \"quia et suscipit\\nsuscipit recusandae consequuntur expedita et cum\\nreprehenderit molestiae ut ut quas totam\\nnostrum rerum est autem sunt rem eveniet architecto\"   }"
            }
          }
        }
      },
      "properties": {}
    }
  }
}

=== Activiti/activiti-cloud/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/resources/process-extensions/RankMovie-extensions-unknown-connector-parameter.json
{
    "id": "process-98ff0720-f94b-40a7-84f6-a9c8fab70568",
    "type": "PROCESS",
    "name": "RankMovie",
    "extensions": {
      "Process_RankMovieId": {
        "properties": {
          "0d9ff66b-4d12-4ec7-b8c6-2082468cd885": {
            "id": "0d9ff66b-4d12-4ec7-b8c6-2082468cd885",
            "name": "movieToRank",
            "type": "string",
            "required": true
          },
          "b6d935ce-6cc8-49f8-8339-8ceece2a48d2": {
            "id": "b6d935ce-6cc8-49f8-8339-8ceece2a48d2",
            "name": "movieDesc",
            "type": "string",
            "required": false
          },
          "fdc1dc9f-9123-4fec-bab7-a938fb01906e": {
            "id": "fdc1dc9f-9123-4fec-bab7-a938fb01906e",
            "name": "rating",
            "type": "integer",
            "required": false
          }
        },
        "mappings": {
          "Task_1spvopd": {
            "inputs": {
              "unknown-input-parameter": {
                "type": "variable",
                "value": "movieToRank"
              }
            },
            "outputs": {
              "movieDesc": {
                "type": "variable",
                "value": "unknown-output-parameter"
              }
            }
          }
        }
      }
    }
}

=== Activiti/activiti-cloud/modeling-acceptance-tests/src/main/resources/process/landing-rover-extensions.json
{
  "id": "process-x",
  "name": "p2",
  "extensions": {
    "properties": {
      "4d4475c9-4150-425b-8a29-1c3532b49215": {
        "id": "4d4475c9-4150-425b-8a29-1c3532b49215",
        "name": "name1",
        "type": "string",
        "value": "",
        "required": false
      },
      "1618c208-75f7-44a1-82c3-23ca34785306": {
        "id": "1618c208-75f7-44a1-82c3-23ca34785306",
        "name": "name2",
        "type": "string",
        "value": "",
        "required": false
      }
    }
  },
  "type": "PROCESS"
}
